### ISSUE TITLE
Creating a new stream fails on demo

### ISSUE THREAD

**Issue by elv-gerald** [eluv-io/elv-live-stream#31]
I am testing the latest changes on demo and noticed I cannot create a new stream object. @elv-serban I think this is related to the new API changes on the backend and the front end needs some retry logic? 

I get this error on the console

```
vendors~main.bundle.js:48 Error: Unable to determine latest version hash for iq__3NBUPtff4aHUw1UK42PFznvcWBPR
    at e.LatestVersionHashV2 (vendors~main.bundle.js:74:32540)
    at async e.PublishContentVersion (vendors~main.bundle.js:116:62462)
    at async e.FinalizeContentObject (vendors~main.bundle.js:116:61262)
    at async g.CallFromFrameMessage (vendors~main.bundle.js:48:16302)
main.js:2 Uncaught (in promise) Unable to determine latest version hash for iq__3NBUPtff4aHUw1UK42PFznvcWBPR
```

```
{
    "name": "ElvHttpClientError",
    "status": 404,
    "statusText": "Not Found",
    "message": "Not Found",
    "url": "https://host-76-74-28-235.contentfabric.io/q/iq__3NBUPtff4aHUw1UK42PFznvcWBPR",
    "body": {
        "errors": [
            {
                "op": "Q.Info",
                "kind": "item does not exist",
                "qhash": "iq__3NBUPtff4aHUw1UK42PFznvcWBPR",
                "cause": {
                    "op": "open reader",
                    "kind": "item does not exist",
                    "qihot": "iq__3NBUPtff4aHUw1UK42PFznvcWBPR",
                    "cause": {
                        "op": "content hash",
                        "kind": "item does not exist",
                        "qid": "iq__3NBUPtff4aHUw1UK42PFznvcWBPR"
                    }
                },
                "stacktrace": [
                    "github.com/qluvio/content-fabric/qfab/daemon/simple/simple_lib.go:265         (*simpleLib).getLatestVersion()",
                    "github.com/qluvio/content-fabric/qfab/daemon/simple/simple_space.go:177       (*simpleSpace).parseIdHashOrToken()",
                    "github.com/qluvio/content-fabric/qfab/daemon/simple/qreader.go:56             (*qReader).openQReaderImpl()",
                    "github.com/qluvio/content-fabric/qfab/daemon/simple/qreader.go:58             (*qReader).openQReaderImpl()",
                    "github.com/qluvio/content-fabric/qfab/daemon/simple/qreader.go:204            (*qReader).info()",
                    "github.com/qluvio/content-fabric/qfab/daemon/simple/qreader.go:206            (*qReader).info()",
                    "github.com/qluvio/content-fabric/qfab/daemon/simple/qreader.go:228            (*qReader).Info()",
                    "github.com/qluvio/content-fabric/qfab/handlers/q_read.go:61                   glob..func38.(*QReadHF).QInfo.func1()",
                    "github.com/gin-gonic/gin@v1.7.7/context.go:168                                (*Context).Next()",
                    "github.com/qluvio/content-fabric/qfab/daemon/middleware/authentication.go:336 BearerTokenAuthHandler.func1()",
                    "github.com/gin-gonic/gin@v1.7.7/context.go:168                                (*Context).Next()",
                    "github.com/qluvio/content-fabric/qfab/daemon/middleware/compress.go:91        Compress.(*compressHF).Middleware.func2()",
                    "github.com/gin-gonic/gin@v1.7.7/context.go:168                                (*Context).Next()",
                    "github.com/qluvio/content-fabric/qfab/daemon/middleware/usage.go:61           UsageHandler.func1()",
                    "github.com/gin-gonic/gin@v1.7.7/context.go:168                                (*Context).Next()",
                    "github.com/qluvio/content-fabric/qfab/daemon/middleware/stats_logger.go:26    HttpStatsLogger.func1()",
                    "github.com/gin-gonic/gin@v1.7.7/context.go:168                                (*Context).Next()",
                    "github.com/qluvio/content-fabric/qfab/daemon/middleware/error.go:32           ErrorHandler.func1()",
                    "github.com/gin-gonic/gin@v1.7.7/context.go:168                                (*Context).Next()",
                    "github.com/qluvio/content-fabric/qfab/daemon/middleware/request_logger.go:47  RequestLogger.func1()",
                    "github.com/gin-gonic/gin@v1.7.7/context.go:168                                (*Context).Next()",
                    "github.com/qluvio/content-fabric/qfab/daemon/middleware/recovery.go:45        Recovery.func1()",
                    "github.com/gin-gonic/gin@v1.7.7/context.go:168                                (*Context).Next()",
                    "github.com/gin-gonic/gin@v1.7.7/gin.go:555                                    (*Engine).handleHTTPRequest()",
                    "github.com/gin-gonic/gin@v1.7.7/gin.go:511                                    (*Engine).ServeHTTP()"
                ]
            }
        ]
    },
    "requestParams": {
        "method": "GET",
        "headers": {
            "Authorization": "Bearer eyJxc3BhY2VfaWQiOiJpc3BjM0FOb1ZTek5BM1A2dDdhYkxSNjlobzVZUFBaVSIsImFkZHIiOiIweDc2MWY0NTI4N2VhMzY0ZGI2YjIxNmJkNjU1OTEwNDMwYWZhM2U4MzkifQ==.RVMyNTZLXzh6cUN1djNlSHBmM2FEalVRUmlCVlRldkFGUjcyY2NiSFNucXFhM0h3bVBKdm81c0ZBRzVvbU40U0pycE1ZN0prS0dkaDhiZnFqQjlZd2JvRXJ2NVhkN3Nw",
            "Accept": "application/json",
            "Content-type": "application/json"
        }
    }
}
```

**Comment by elv-zenia** [comment]
Relates to https://github.com/eluv-io/elv-client-js/commit/1437c948328857bbc0e06bf0897ed926f5326883
Deployed to demo and prod-dev.

**Comment by elv-gerald** [comment]
Verified fix is working. Also tested on prod dev to make sure existing prod environment works with the change.
