### ISSUE TITLE
Error when applying ladder to new stream

### ISSUE THREAD

**Issue by elv-gerald** [eluv-io/elv-live-stream#74]
On Demo I noticed I cannot apply the m6 ladder to my stream. Here are the steps to reproduce
1. Create a new stream without specifying a ladder (use default). I used a UDP stream. 
2. Probe/config the incoming stream
3. Open the stream detail view and apply the m6 profile

I will get a failure notification with the following in the console 
```
index-BCttwesI.js:200 Unable to apply settings TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Ake.<anonymous> (index-BCttwesI.js:260:8202)
    at VO (index-BCttwesI.js:42:6173)
    at ObservableObject.key (index-BCttwesI.js:42:5992)
    at Ake.<anonymous> (index-BCttwesI.js:260:4147)
    at Generator.next (<anonymous>)
    at VO (index-BCttwesI.js:42:6173)
    at <unnamed flow> - runid: 215 - yield 4 (index-BCttwesI.js:42:5992)
    at v (index-BCttwesI.js:42:22998)
```

**Comment by elv-gerald** [comment]
This only seems to happen ONLY after creation.
I recreated the issue but after running then stopping the stream, changing the ladder works and does not error out.

**Comment by elv-gerald** [comment]
Looks fixed. Will close when deployed to pord.
