### ISSUE TITLE
Refactor issues

### ISSUE THREAD

**Issue by elv-gerald** [eluv-io/elv-live-stream#79]
This ticket is for minor issues we spot for the code refactor.

**Comment by elv-gerald** [comment]
The spacing for the back button on the preview page looks a little uneven. Any way to move the text a bit more to the left? It looks close to being cut off on the right or add some buffer room on the right. 
![image](https://github.com/user-attachments/assets/647039fd-7a88-4b6b-91a7-436aaf2b0c9c)

**Comment by elv-gerald** [comment]
One small change we mentioned on slack. Sort all stream by "name" on all the applicable pages. We can ignore "display_title"

**Comment by elv-zenia** [comment]
Deployed fixes for the above two issues.

**Comment by elv-gerald** [comment]
Found one small one with the creation form. If I try to create a stream and pick an item from the dropdown, sometimes the url wont clear when I switch streaming protocol. 

See video below, I pick a UDP url but when I swap to other protocls it stays present. Eventually the form goes back to blank


https://github.com/user-attachments/assets/9e8f59e6-89c7-4eba-8fce-052d46844b38

**Comment by elv-gerald** [comment]
Some other small things on the creation form

Typo for "Select Encryption" in the placeholder text, it showsd "Selet" instead of "Select"
![Screenshot 2024-12-18 at 2 37 59 PM](https://github.com/user-attachments/assets/67e12325-3f54-421d-bbf3-67d330ede2a1)


For Retention it is showing as blank on initial load (even though it uses 1 day)
![Screenshot 2024-12-18 at 2 37 41 PM](https://github.com/user-attachments/assets/5175b560-6ea9-4549-9c84-1da7c367b131) 
On Prod we pre select 1 day

<img width="812" alt="Screenshot 2024-12-18 at 2 37 46 PM" src="https://github.com/user-attachments/assets/69bf3d1b-42f7-4b61-9d0b-19db24e4cdff" />

**Comment by elv-zenia** [comment]
Deployed fixes for the typo and retention default.

**Comment by elv-zenia** [comment]
Deployed a fix for the bug where selected url doesn't clear when switching protocols.

**Comment by elv-gerald** [comment]
I noticed on the refactor the creation form is more narrow in terms of width when compared to prod. Below is a screenshot, of demo (top) vs prod. I made sure the browser size settings  are set 100% to get an apples to apples comparison

![Screenshot 2024-12-18 at 5 01 36 PM](https://github.com/user-attachments/assets/4953c043-c0c6-44c7-bd3b-6848d98a7b6f)

**Comment by elv-gerald** [comment]
I get an error when I try the probe step from the stream creation step. 
![image](https://github.com/user-attachments/assets/1b1e306e-7241-4ecb-b428-ddc5c022e338)

I see the console complains with this but in the creation form I had a library specified. 
```
Error: Library ID not specified
    at t.ValidateLibrary (851.bundle.js:2:246151)
    at e.<anonymous> (851.bundle.js:2:440804)
    at d (851.bundle.js:2:423693)
...
```

**Comment by elv-gerald** [comment]
When I try to create a stream with no library specified the UI is no longer informing me of my error. Instead a console error get thrown with no error feedback to the user

https://github.com/user-attachments/assets/3dcce60c-faba-48e0-b56e-db65aae17169

**Comment by elv-gerald** [comment]
On the creation form, for advanced values where we have defaults set for Retention, DRM, Ladder. I noticed that sometimes when I change the value for one of the dropdowns the UI clears my selection or ignored my choice and shows the default value.  I sometimes have to select a non default value twice for it to proper show as selected for me. 

Below is a video that shows the issue, I see no console errors getting thrown

https://github.com/user-attachments/assets/6f2e8ddb-10c3-4921-9d4e-5f9b8e0afae8

**Comment by elv-zenia** [comment]
Deployed fixes for:
- `the creation form is more narrow in terms of width when compared to prod`
- ` I get an error when I try the probe step from the stream creation step.`

**Comment by elv-zenia** [comment]
Deployed a fix for:
- advanced values not getting set properly on the Create page

**Comment by elv-zenia** [comment]
Deployed a fix for:
- `When I try to create a stream with no library specified the UI is no longer informing me of my error`
PLUS general validation for the Create form items

**Comment by elv-gerald** [comment]
I pulled the latest changes an noticed in the advanced settings the default ladder is preselected (as expected) but the drop down is blank.  When I click on it you can see "default" is selected and when I click off the drop down it gets populated.

https://github.com/user-attachments/assets/cbaf40d9-591b-4eb3-aada-bbe3819b6827

**Comment by elv-gerald** [comment]
On demo for stream creation default value for permissions is editable but not auto selected but on prod it is

This is what the option shows on initial load
demo
<img width="841" alt="Screenshot 2024-12-19 at 1 16 18 PM" src="https://github.com/user-attachments/assets/4149f7dd-8ad3-420a-9644-ea0fa4ee0bdd" />

prod
<img width="858" alt="Screenshot 2024-12-19 at 1 16 27 PM" src="https://github.com/user-attachments/assets/3340e95a-eb68-48b6-8e37-6804a49c94eb" />

**Comment by elv-gerald** [comment]
When creating a new stream. If I go through the whole probe process I noticed 2 issues
- My custom language and setting a track to default do not get applied after the stream is saved
- /probe gets called again when I click save (this already after I already probed the first time)

Below is an example of the 2 things above. You can see the browser console that probe gets called again when I click save, I ended up sending the stream again so the probe get fulfilled.

You can also see after the save is done my custom language and setting the audio track as default are not present.




https://github.com/user-attachments/assets/f725b21f-e35b-48e8-97f8-8e63b1e02ef3

**Comment by elv-zenia** [comment]
Deployed fixes for:
- in the advanced settings the default ladder is preselected (as expected) but the drop down is blank
- default value for permissions is editable but not auto selected
- For Create -> Probe, do not re-probe when saving
- For Create -> Probe, save custom language and default track
- Fix `audio_index` meta when disabling Record on a middle audio track

**Comment by elv-zenia** [comment]
Deployed a change to the Preview page to not use a "live" player profile by default. You'll notice that the value of HLS Player Profile in the right sidebar will now be Default.

**Comment by elv-gerald** [comment]
On the creation page for advanced I cannot change the ladder profile anymore. It stays stuck on the "default" ladder 

https://github.com/user-attachments/assets/f2263626-c195-4900-b1a3-18719ffd2e8b

**Comment by elv-zenia** [comment]
Deployed a fix for the ladder profile being stuck on "default"

**Comment by elv-gerald** [comment]
> Deployed a fix for the ladder profile being stuck on "default"

Interesting, Its fixed but now the issue where the dropdown is blank is back.
![image](https://github.com/user-attachments/assets/0c01da30-b25e-4932-84ab-5dd56a8356e6)

**Comment by elv-zenia** [comment]
Deployed a fix for the playout ladder being blank again

**Comment by elv-gerald** [comment]
deployed to prod
